### ISSUE TITLE
DynamicShop v3.116.1 error

### ISSUE THREAD

**Issue by yuankun1** [7sat/DynamicShop3#86]
[18:42:02] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to DynamicShop v3.116.1
 org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[forge:?]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:593) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:578) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:430) ~[forge:?]
        at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:407) ~[?:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1402) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38) ~[?:?]
        at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:885) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:868) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:862) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(SourceFile:127) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:848) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:779) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_361]
Caused by: java.lang.ClassCastException: org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockEntityState cannot be cast to org.bukkit.block.Sign
        at me.sat7.dynamicshop.events.OnSignClick.onInteract(OnSignClick.java:124) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor311.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_361]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_361]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[forge:?]
        ... 22 more
I don't know if there's a problem with this bug, but my server players have already swiped hundreds of thousands of game coins
I don't know if this error will make my players spend a lot of in-game currency

**Comment by 7sat** [comment]
As far as I know, PlugMan or other similar plugins cause this problem.
Try restarting the server 'properly'.
Please let me know if the problem persists.

**Comment by yuankun1** [comment]
> 据我所知，PlugMan或其他类似的插件会导致此问题。尝试“正确”重新启动服务器。如果问题仍然存在，请告诉我。

The reboot is still the same

**Comment by 7sat** [comment]
I'm going to dig deeper into this log. While I'm looking at the problem, you might want to check the following: Make sure your shop sign is properly named. It is case sensitive. If everything looks fine, delete the sign.yml file (make a backup) and right-click the sign to recreate the data. (Don't try this if you have a lot of shop signs, this can be cumbersome)
